version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  m1sevicepayament:
    container_name: m1sevicepayament
    build:
      context: ./m1sevicepayament
      dockerfile: Dockerfile
    depends_on:
      - rabbitmq
    ports:
      - "8080:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
